title = "Chess Coders | Modern software solutions"
theme = "ion"
languageCode = "en-US"
enableRobotsTXT = true

[params]
  author = "Victor Ocnarescu"
  fonts = "https://fonts.googleapis.com/css?family=Libre+Baskerville|Roboto&display=swap"
  sitename = "Chess Coders"
  description = "Modern software solutions"
  image = "/chesscoders-wallpaper.jpg"
  favicon = "favicon.ico"
  analytics = "UA-127399322-1"
  fontAwesome = true
  headingFont = "'Libre Baskerville', serif"
  bodyFont = "'Roboto', sans-serif"
  primaryColor = "#007b85"
  secondaryColor = "#4252b1"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 100
  [[menu.main]]
    name = "About us"
    url = "#who-we-are"
    weight = 110
  [[menu.main]]
    name = "Services"
    url = "#our-services"
    weight = 120
  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio"
    weight = 130
  [[menu.main]]
    name = "Our Team"
    url = "#our-team"
    weight = 140
  [[menu.main]]
    name = "Our Process"
    url = "#our-process"
    weight = 150
  [[menu.main]]
    name = "Contact us"
    url = "#contact-us"
    weight = 160
