baseUrl = "https://chesscoders.netlify.com"
title = "Chess Coders | Modern software solutions"
theme = "carbon"
languageCode = "en-US"
enableRobotsTXT = true

[params]
  author = "Victor Ocnarescu"
  fonts = "https://fonts.googleapis.com/css?family=Libre+Baskerville|Source+Sans+Pro&display=swap"
  sitename = "Chess Coders"
  description = "Modern software solutions"
  image = "/chesscoders-wallpaper.jpg"
  favicon = "favicon.ico"
  analytics = "UA-127399322-1"
  fontAwesome = true

[menu]
  [[menu.home]]
    name = "About us"
    url = "#who-we-are"
  [[menu.home]]
    name = "Portfolio"
    url = "/portfolio"
