---
new_page_extension: md
auto_deploy: false
admin_path: content/admin
webhook_url:
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/portfolio
  label: Portfolio
  create: all
  match: "**/*"
- type: directory
  path: content/home
  label: Home sections
  create: all
  match: "**/*"
- type: directory
  path: content/technologies
  label: Technologies
  create: all
  match: "**/*"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.57.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server --renderToDisk --port 8080 --bind 0.0.0.0
version: 0.57.2
